sonar.projectKey=ssu-commerce-core
sonar.sources=ssu-commerce-cores/ssu-commerce-core-jpa/src/main, ssu-commerce-cores/ssu-commerce-core-security/src/main, ssu-commerce-cores/ssu-commerce-core-web/src/main
sonar.tests=ssu-commerce-cores/ssu-commerce-core-jpa/src/test, ssu-commerce-cores/ssu-commerce-core-security/src/test, ssu-commerce-cores/ssu-commerce-core-web/src/test
sonar.language=kotlin
